### ISSUE TITLE
Prepare Project Proposal and Class Diagram

### ISSUE THREAD

**Issue by marmikpatel2621** [cm7cd/UMKC-IS-Guide#1]
We have decided to create UMKC International Student Guide application which helps International Student when they will reach Kansas City. After some suggestions, we finalized to create UMKC International Student Guide which guides international  students starting, from their GRE/TOEFL exam preparation to post departure.

**Comment by arunitgupta** [comment]
Class Diagram Completed.

**Comment by arunitgupta** [comment]
Revised Project Proposal Completed.

**Comment by arunitgupta** [comment]
Working on first Increment Report.

**Comment by arunitgupta** [comment]
Report completed.
